name: Update README with .sh scripts list

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: List .sh files in repo root
      id: list_scripts
      run: |
        FILES=$(git ls-files '*.sh')
        echo "files<<EOF" >> $GITHUB_OUTPUT
        echo "$FILES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate new README section
      id: gen_readme
      run: |
        echo "# bash-tools" > new_readme_section.md
        echo "" >> new_readme_section.md
        echo "### Scripts:" >> new_readme_section.md

        while IFS= read -r file; do
          base=$(basename "$file" .sh)
          echo "### $base :" >> new_readme_section.md
          echo '```bash' >> new_readme_section.md
          echo "bash <(curl -Ls https://raw.githubusercontent.com/s7net/bash-tools/main/$file)" >> new_readme_section.md
          echo '```' >> new_readme_section.md
          echo "" >> new_readme_section.md
        done <<< "${{ steps.list_scripts.outputs.files }}"

    - name: Update README.md
      run: |
        if [ ! -f README.md ]; then
          echo "# bash-tools" > README.md
          echo "" >> README.md
          echo "<!-- scripts start -->" >> README.md
          cat new_readme_section.md >> README.md
          echo "<!-- scripts end -->" >> README.md
        else
          awk '
          BEGIN {inblock=0}
          /<!-- scripts start -->/ {print; system("cat new_readme_section.md"); inblock=1; next}
          /<!-- scripts end -->/ {inblock=0; next}
          inblock==0 {print}
          ' README.md > README.new.md
          mv README.new.md README.md
        fi

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update README with latest .sh scripts list"
        branch: main
        file_pattern: README.md
        commit_user_name: s7net
        commit_user_email: s7net@users.noreply.github.com
        token: ${{ secrets.PAT_TOKEN }}
